Naren update User Guide bugs
AY2223S1-CS2103T-W12-3/tp pull request #280
Opened 2022-11-02 10:12 UTC by nareus

2022-11-03 04:09 UTC, nealetham requested changes
Just a minor change required.

2022-11-03 04:09 UTC, nealetham commented on docs/UserGuide.md
> +* Do not include any file types in the `FOLDER_NAME` or `FILE_NAME`.
Should we use the term file extension? Is that too technical for the user?

2022-11-03 04:09 UTC, nealetham commented on docs/UserGuide.md
> +* Do not include any file types in the `FOLDER_NAME` or `FILE_NAME`.
On second thought, it might be too technical. One way we can dumb it down is to state that the file type is anything beyond the dot i.e. .json

2022-11-04 16:13 UTC, jq1836 commented on docs/UserGuide.md
> +* Do not include any file types in the `FOLDER_NAME` or `FILE_NAME`. A file type is the description that comes after the`.` in a file. For example, The file name of the file `residents.csv` is  just
Minor issue here with the "the`.`" part, there should be a whitespace.

2022-11-04 16:14 UTC, jq1836 approved these changes
LGTM! Just that minor typo.

2022-11-04 16:23 UTC, jq1836 commented on docs/UserGuide.md
> +* Do not include any file types in the `FOLDER_NAME` or `FILE_NAME`. A file type is the description that comes after the`.` in a file. For example, The file name of the file `residents.csv` is  just
Also, there is an extra whitespace towards the end.

".... `residents.csv` is  just `residents`."

2022-11-05 03:39 UTC, nealetham approved these changes
Looks good!

2022-11-05 04:16 UTC, merged